### ISSUE TITLE
Skip auth for preflight requests

### ISSUE THREAD

**Issue by knopkem** [fastify/fastify-bearer-auth#165]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

![image](https://github.com/fastify/fastify-bearer-auth/assets/994526/c06584d5-ddc8-4e7e-9d4c-5c055b3fff06)

authorization for preflight requests make no sense

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Uzlopak** [comment]
You should set bearer auth authorization not on plugin level but on route level.

**Comment by Fdawgs** [comment]
Hi @knopkem, did you managed to solve this?

If you want to set it at the plugin level instead of the route level, your best bet would be to do something similar the example in [Integration with @fastify/auth](https://github.com/fastify/fastify-bearer-auth?tab=readme-ov-file#integration-with-fastifyauth) section of the readme, but instead of using `@fastify/auth` and decorating the request, simply adding a `preHandler` hook:

```js
await fastify
  .register(auth)
  .register(bearerAuthPlugin, {
    addHook: false,
    keys,
    verifyErrorLogLevel: "debug",
  })

  fastify.addHook("preHandler", (req, res, done) => {
	if (req.method !== "OPTIONS") {
	  return securedContext.verifyBearerAuth(req, res, done)
	}
	return done()
  })
```

**Comment by jsumners** [comment]
I am closing this as a misconfiguration issue. Please review https://fastify.dev/docs/latest/Reference/Encapsulation/
